
import json


#music subreddits by category taken from https://www.reddit.com/r/Music/wiki/musicsubreddits?v=7c76568c-7126-11e6-b679-0e0470a21327


string1="""/r/baroque
/r/classicalmusic
/r/contemporary
/r/concertband
/r/choralmusic
/r/ChamberMusic
/r/EarlyMusic
/r/earlymusicalnotation
/r/ElitistClassical
/r/icm
/r/Opera
/r/orchestra"""


string2="""/r/acidhouse
/r/ambientmusic
/r/AStateOfTrance
/r/AtmosphericDnB
/r/BigBeat
/r/boogiemusic 
/r/breakbeat
/r/breakcore
/r/chicagohouse
/r/chillout
/r/Chipbreak
/r/Chiptunes
/r/complextro
/r/cxd 
/r/darkstep
/r/deephouse
/r/DnB
/r/DubStep
/r/EDM
/r/EBM 
/r/electronicdancemusic
/r/ElectronicJazz
/r/ElectronicBlues
/r/electrohiphop
/r/electrohouse
/r/electronicmagic
/r/ElectronicMusic
/r/electropop
/r/electroswing
/r/ExperimentalMusic
/r/fidget
/r/filth
/r/frenchelectro
/r/frenchhouse
/r/funkhouse
/r/fusiondancemusic
/r/futurebeats
/r/FutureFunkAirlines
/r/FutureGarage
/r/futuresynth
/r/gabber
/r/glitch
/r/glitchop
/r/Grime
/r/happyhardcore
/r/hardhouse
/r/hardstyle
/r/house
/r/idm
/r/industrialmusic
/r/ItaloDisco
/r/latinhouse
/r/LiquidDubstep
/r/mashups
/r/melodichouse
/r/minimal
/r/mixes
/r/moombahcore
/r/nightstep
/r/OldskoolRave 
/r/Outrun
/r/theOverload 
/r/partymusic
/r/plunderphonics
/r/psybient
/r/PsyBreaks
/r/psytrance
/r/purplemusic
/r/raggajungle
/r/RealDubstep
/r/skweee
/r/swinghouse
/r/tech_house
/r/Techno
/r/Trance
/r/tranceandbass
/r/trap
/r/tribalbeats
/r/TropicalHouse
/r/ukfunky
/r/witchhouse
/r/wuuB"""


string3="""/r/80sHardcorePunk
/r/90sAlternative
/r/90sPunk
/r/90sRock
/r/AlternativeRock
/r/AltCountry
/r/AORMelodic
/r/ausmetal 
/r/BlackMetal
/r/bluegrass
/r/Blues
/r/bluesrock
/r/Boneyard 
/r/CanadianClassicRock
/r/CanadianMusic
/r/ClassicRock
/r/country
/r/Christcore
/r/crunkcore
/r/deathcore
/r/deathmetal
/r/Djent
/r/DoomMetal
/r/Drone
/r/Emo
/r/EmoScreamo
/r/epicmetal
/r/flocked 
/r/folk
/r/folkmetal
/r/folkpunk
/r/folkrock
/r/folkunknown
/r/GaragePunk
/r/GothicMetal
/r/Grunge
/r/hardcore
/r/HardRock
/r/horrorpunk 
/r/indie_rock
/r/jrock
/r/krautrock
/r/LadiesofMetal
/r/MathRock
/r/melodicdeathmetal
/r/MelodicMetal
/r/MetalNews
/r/Metalmusic
/r/metal
/r/metalcore
/r/ModernRockMusic
/r/monsterfuzz
/r/neopsychedelia
/r/NewWave
/r/noiserock
/r/numetal
/r/pianorock
/r/poppunkers
/r/PostHardcore
/r/PostRock
/r/powermetal
/r/powerpop
/r/ProgMetal
/r/progrockmusic
/r/PsychedelicRock
/r/punk
/r/Punkskahardcore
/r/Punk_Rock
/r/raprock 
/r/Rock
/r/shoegaze
/r/stonerrock
/r/symphonicblackmetal
/r/symphonicmetal
/r/synthrock
/r/ThrowbackCore
/r/truethrash
/r/Truemetal
/r/OutlawCountry
/r/WomenRock"""


string4="""/r/80sHipHop
/r/90sHipHop
/r/altrap
/r/asianrap
/r/backpacker
/r/backspin
/r/BayRap
/r/ChapHop
/r/ChiefKeef
/r/DrillandBop
/r/Emo_Trap
/r/Gfunk
/r/hiphopheads
/r/hiphopheadsnorthwest
/r/hiphop101
/r/MemphisRap
/r/NYrap
/r/Rap
/r/raprock
/r/rapverses
/r/rhymesandbeats
/r/trapmuzik
/r/ukhiphopheads
/r/undergroundchicago
/r/LofiHipHop"""


string5="""/r/2010smusic
/r/2000smusic
/r/90sMusic
/r/80sremixes
/r/80sMusic
/r/70sMusic
/r/70s
/r/60sMusic
/r/50sMusic"""


string6="""/r/AfricanMusic
/r/afrobeat
/r/balkanbrass
/r/balkanmusic
/r/brazilianmusic
/r/britpop
/r/CroatianMusic
/r/Flamenco
/r/international_music
/r/Irishmusic
/r/ItalianMusic
/r/jpop 
/r/KoreanRock
/r/kpop 
/r/RoMusic 
/r/spop 
/r/somluso 
/r/UKbands
/r/WorldMusic"""


string7="""/r/Acappella
/r/AcousticCovers
/r/ambientfolk
/r/animemusic
/r/BestOfDisney
/r/boomswing
/r/bossanova
/r/carmusic
/r/concerts
/r/chillmusic
/r/cpop
/r/Complextro
/r/dembow
/r/disco
/r/DreamPop
/r/dub
/r/Elephant6
/r/ETIMusic
/r/Exotica
/r/FilmMusic
/r/FunkSouMusic
/r/gamemusic
/r/GamesMusicMixMash
/r/GunslingerMusic
/r/GypsyJazz
/r/IndieFolk
/r/jambands
/r/jazz
/r/JazzFusion
/r/JazzInfluence
/r/listentoconcerts
/r/klezmer
/r/lt10k
/r/MedievalMusic
/r/MelancholyMusic
/r/minimalism_music
/r/motown
/r/MusicForConcentration
/r/muzyka
/r/NuDisco
/r/oldiemusic
/r/OldiesMusic 
/r/pianocovers
/r/popheads 
/r/PoptoRock
/r/QuietStorm
/r/rainymood
/r/recordstorefinds
/r/reggae
/r/remixxd
/r/RetroMusic
/r/rnb
/r/rootsmusic
/r/SalsaMusic
/r/Ska
/r/Soca 
/r/songbooks
/r/Soulies
/r/SoulDivas
/r/SoundsVintage
/r/SpaceMusic
/r/SurfPunk
/r/swing
/r/Tango
/r/TheRealBookVideos
/r/TouhouMusic
/r/TraditionalMusic
/r/treemusic
/r/triphop
/r/vaporwave
/r/VintageObscura 
/r/vocaloid"""


string8="""/r/audioinsurrection 
/r/albumaday
/r/albumoftheday 
/r/Albums
/r/albumlisteners
/r/bassheavy
/r/BinauralMusic
/r/BoyBands
/r/Catchysongs
/r/Chopping
/r/CircleMusic
/r/CoverSongs
/r/cyberpunk_music
/r/DANCEPARTY
/r/danktunes
/r/deepcuts 
/r/EarlyMusic
/r/earlymusicalnotation 
/r/FemaleVocalists
/r/festivals
/r/findaband
/r/FitTunes 
/r/FreeAlbums
/r/freemusic
/r/Frisson
/r/gameofbands
/r/GayMusic
/r/germusic 
/r/gethightothis
/r/GuiltyPleasureMusic
/r/HeadNodders
/r/heady
/r/HeyThatWasIn
/r/HighFidelity
/r/ifyoulikeblank
/r/ilikethissong
/r/indie 
/r/IndieWok
/r/Indieheads
/r/Instrumentals
/r/ipm
/r/IsolatedVocals
/r/LeeHallMusic
/r/LetsTalkMusic
/r/listentoconcerts
/r/listentodynamic 
/r/listentomusic
/r/listentonews
/r/ListenToThis
/r/ListenToUs
/r/livemusic
/r/llawenyddhebddiwedd 
/r/LongerJams
/r/Lyrics
/r/mainstreammusic
/r/makemeaplaylist 
/r/MiddleEasternMusic
/r/MLPtunes
/r/Music
/r/MusicAlbums 
/r/musicanova 
/r/musicsuggestions
/r/MusicToSleepTo
/r/musicvideos
/r/NameThatSong
/r/NewAlbums 
/r/newmusic
/r/onealbumaweek
/r/partymusic
/r/RedditOriginals
/r/RepublicOfMusic
/r/RoyaltyFreeMusic
/r/runningmusic
/r/ScottishMusic
/r/SlavicMusicVideos
/r/songwriterscircle 
/r/SpotifyMusic 
/r/ThemVoices
/r/TodaysFavoriteSong
/r/unheardof
/r/WhatIListenTo
/r/WTFMusicVideos"""


string9="""/r/AlbumArtPorn
/r/albumreviews
/r/Audio
/r/Audiophile
/r/audiophilemusic
/r/AustinMusicians
/r/bandmembers
/r/CarAV
/r/CassetteCulture
/r/Cd_collectors
/r/ConcertTickets
/r/germusic 
/r/glastonbury_festival
/r/ICoveredASong
/r/ifyoulikeblank
/r/independentmusic
/r/ineedasong/
/r/japanesemusic
/r/Jazzguitar 
/r/koreanmusic
/r/LubbockMusicians 
/r/mixcd
/r/musiccritics
/r/MusicalComedy
/r/musicessentials
/r/MusicEventMeetUp
/r/musicfestivals
/r/musicnews
/r/MusiciansBlogs
/r/Musicians
/r/MusicProduction
/r/NeedVocals 
/r/OSOM
/r/performer
/r/RecordClub
/r/recordstore
/r/redditmusicclub
/r/Rockband
/r/RockbandChallenges
/r/TheSongRemainsTheSame
/r/TipOfMyTongue
/r/TouringMusicians
/r/vinyl
/r/VinylReleases
/r/WeAreTheMusicMakers"""


string10="""/r/311
/r/ADTR 
/r/AliciaKeys
/r/ArcadeFire
/r/ArethaFranklin
/r/APerfectCircle
/r/AvengedSevenfold
/r/TheAvettBrothers
/r/BABYMETAL
/r/Bangtan
/r/BaysideIsACult
/r/TheBeachBoys
/r/Beatles
/r/billytalent
/r/Blink182
/r/BMSR
/r/BoBurnham
/r/boniver
/r/brandnew
/r/BruceSpringsteen
/r/Burial
/r/ChanceTheRapper
/r/cher
/r/ChiefKeef
/r/ChristinaAguilera
/r/cityandcolour
/r/Coldplay
/r/CutCopy
/r/TheCure
/r/DaftPunk
/r/DavidBowie
/r/Deadmau5
/r/DeathCabforCutie
/r/DeathGrips
/r/DeepPurple
/r/Deftones 
/r/DieAntwoord
/r/DMB 
/r/donaldglover 
/r/Drizzy
/r/elliegoulding
/r/Eminem
/r/empireofthesun
/r/EnterShikari
/r/Evanescence
/r/FallOutBoy
/r/feedme
/r/FirstAidKit
/r/flaminglips
/r/fleet_foxes
/r/Foreigner
/r/FrankOcean
/r/franzferdinand
/r/finkworld
/r/Ghostbc
/r/Gorillaz
/r/grateful_dead
/r/Greenday
/r/GunsNRoses
/r/Incubus
/r/JackJohnson
/r/JackWhite
/r/JanetJackson
/r/JackJohnson
/r/Kanye
/r/KendrickLamar
/r/kings_of_leon
/r/Korn
/r/ladygaga
/r/lanadelrey
/r/lennykravitz
/r/Led_Zeppelin
/r/lorde
/r/macdemarco
/r/Macklemore
/r/Madonna
/r/Madlib
/r/Manowar
/r/MariahCarey
/r/MattAndKim
/r/Megadeth
/r/Metallica
/r/mfdoom
/r/MGMT
/r/MichaelJackson
/r/MinusTheBear
/r/ModestMouse
/r/Morrissey
/r/mrbungle
/r/MyChemicalRomance
/r/Muse
/r/NeilYoung
/r/NIN
/r/Nirvana
/r/NOFX
/r/oasis
/r/officialbadcompany
/r/ofMontreal
/r/OfMonstersAndMen
/r/OFWGKTA 
/r/Opeth
/r/OutKast
/r/panicatthedisco
/r/PearlJam
/r/phish
/r/Pinback 
/r/PinkFloyd
/r/ThePolice
/r/porcupinetree
/r/prettylights
/r/Puscifer
/r/Queen
/r/Radiohead
/r/RATM
/r/RedHotChiliPeppers
/r/RelientK
/r/rhymesandbeats
/r/RiseAgainst
/r/robertplant
/r/SaveMoneyCrew
/r/SigurRos
/r/Slayer
/r/slipknot
/r/SmashingPumpkins
/r/SOCOTRAband
/r/SparksFTW
/r/TameImpala
/r/TaylorSwift
/r/TeganAndSara
/r/TheKillers
/r/TheMagneticZeros
/r/TheOffspring
/r/thepixies
/r/The_Residents
/r/TheStrokes
/r/TheWeeknd
/r/tmbg 
/r/ToolBand
/r/tragicallyhip
/r/trunknation 
/r/TwentyOnePilots
/r/U2Band
/r/Umphreys
/r/UnicornsMusic
/r/velvetunderground
/r/Ween 
/r/weezer
/r/WeirdAl
/r/yesband
/r/Zappa"""


list_of_strings=[string1,string2,string3,string4,string5,string6,string7,string8,string9,string10]
types=["Classical","Electronic,","RockMetal","Hip-Hop","Decades","RegionCulture","Misc","Any_Genre","Community","ArtistBand"]

subreddit_dict={}
for index,string in enumerate(list_of_strings):
    list_of_reddits=string.split("\n")
    list_of_reddits=[x[3:] for x in list_of_reddits]
    for x in list_of_reddits:
        if "jazz" in x or "Jazz" in x:
            subreddit_dict[x]="Jazz"
        elif "Punk" in x or "punk "in x:
            subreddit_dict[x]="Punk"
        if "pop" in x or "Pop" in x:
            subreddit_dict[x]="Pop"
        else:
            subreddit_dict[x]=types[index]



with open('subreddits.json', 'w') as fp:
    json.dump(subreddit_dict, fp)
print("done")